# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Install mkcert
      run: |
        sudo apt-get install libnss3-tools
        wget https://dl.filippo.io/mkcert/latest?for=linux/amd64 -O mkcert
        chmod +x mkcert
        sudo mv mkcert /usr/local/bin/

      - name: Set up local CA and generate certificates
        run: |
          mkcert -install
    - run: npm run makecerts
    - run: npm run build --if-present
    - run: npm test
